apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: boop-microservice
  namespace: your-project-id
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    spec:
      containers:
        - image: gcr.io/your-project-id/boop-microservice
          ports:
            - containerPort: 8080
          env:
            - name: FIREBASE_SERVICE_ACCOUNT_BASE64
              value: ${FIREBASE_SERVICE_ACCOUNT_BASE64} # Set this as a secret in Cloud Run or use Cloud Secret Manager
            - name: MASTER_DELETE_SECRET
              value: ${MASTER_DELETE_SECRET}
          resources:
            limits:
              memory: 512Mi
              cpu: 1
